services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: smartqr
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: smartqr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartqr -d smartqr"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  postgres_data:
